### PR TITLE
remove some duplicate code

### PR DESCRIPTION
**Pull request by microlv**
FYI

### CODE REVIEW

**Comment by mikrofusion** [comment]
Thanks for the PR @microlv!  Can you rebase off of master and I'll merge your changes (there was another outstanding PR that I merged in this morning)?

**Comment by microlv** [comment]
Hi, I merge the new code~^_^, have a check~

**Comment by mikrofusion** [comment]
@microlv hmm, it appears you no longer have any files to merge?  Did you do a merge instead of a rebase?  Can you try again off master?

screen shot 2015-12-29 at 8 59 10 am

**Comment by microlv** [comment]
@mikrofusion I sorry about that... I make a mistake.
when I merge the code, I resolve conflict by using other people and forgot merge my code...
>_<

**Comment by mikrofusion** [comment]
@microlv thanks!

**Pull request merged**
